config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#welcome'
  get 'welcome/:name', to: 'static_pages#welcome'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/home', to: 'static_pages#home'
  get '/gossip/:gossip_id', to: 'static_pages#gossip', as: 'gossip'
  get '/author/:author_id', to: 'static_pages#author', as: 'author'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
    has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_tag_gossips
  has_many :tags, through: :join_tag_gossips
  has_many :comments
  has_many :likes
end

app/models/join_message_recipient.rb
class JoinMessageRecipient < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
    belongs_to :tag 
    belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip, optional: true
    belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :join_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_gossips
  has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
    @name = params[:name]
  end

  def team
  end

  def contact
  end

  def home
  end

  def gossip
    @gossip = Gossip.find(params[:gossip_id])
  end

  def author
    @author = User.find(params[:author_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/">The gossip project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto"
            <li class="nav-item">
              <%=  link_to "Team", team_path, :class => "py-2 d-none d-md-inline-block" %>
            </li>
            <li class="nav-item">
              <%=  link_to "Contact", contact_path, :class => "py-2 d-none d-md-inline-block" %>
            </li>
            <li class="nav-item">
              <%=  link_to "Home", home_path, :class => "py-2 d-none d-md-inline-block" %>
            </li>
          </ul>
        </div>
      </nav>
      <div class="container" style="padding-top: 5rem;">
        <%= yield %>
      </div>
  </body>
</html>

app/views/static_pages/author.html.erb
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
</head>
<body class="text-center">
  <h1 class="display-4 text-center">Informations sur l'auteur <%= @author.first_name %></h1>
  <hr></br>
  <ul>
    <li>Nom complet : <%= @author.first_name %> <%= @author.last_name %></li>
    <li>Age : <%= @author.age %></li>
    <li>Ville : <%= @author.first_name %></li>
    <li>Description : <%= @author.description %></li>
    <li>Email : <%= @author.email %></li>
  </ul>        

</body>
</html>

app/views/static_pages/contact.html.erb
Facebook
Instagram
thp_thib@gmail.com
thp_claire@gmail.com

app/views/static_pages/gossip.html.erb
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
</head>
<body class="text-center">
  <h1 class="display-4">Gossip n°<%= @gossip.id %></h1><br/>
  <h3><< <%= @gossip.content %> >></h3>
  <br/><hr><br/>
  <ul>
    <li>Titre : <%= @gossip.title %></li>
    <li>Auteur : <%= link_to @gossip.user.first_name, author_path(@gossip.user.id) %></li>
    <li>Date de création : <%= @gossip.created_at %></li>
  </ul>        
</body>
</html>

app/views/static_pages/home.html.erb
<h1 class="display-4 text-center">Les derniers potins en date</h1><br/>
<div class="card-columns">
  <% Gossip.all.each do |gossip| %>
    <div class="card bg-light p-3">
      <blockquote class="blockquote mb-0 card-body">
        <p><%= link_to gossip.title, gossip_path(gossip.id) %></p>
        <footer class="blockquote-footer">
          <small class="text-muted">
            <%= gossip.user.first_name %>
          </small>
        </footer>
      </blockquote>
    </div>
  <% end %>
</div>

app/views/static_pages/team.html.erb
<p>voici notre équipe lol mdr 😇❤️😻</p>

app/views/static_pages/welcome.html.erb
<h1>Bienvenue <%= @name %> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>